### ISSUE TITLE
align source image with the first frame of driver video

### ISSUE THREAD

**Issue by maliho0803** [AliaksandrSiarohin/mtm#23]
do you have any good strategy for aligning source image with the first frame of driver video

**Comment by AliaksandrSiarohin** [comment]
I don't know any good general stratefy. Here there is some strategy for faces https://github.com/AliaksandrSiarohin/first-order-model/blob/master/demo.py , e.g --find_best_frame

**Comment by maliho0803** [comment]
thank you very much for your reply! one more question, if i predict more keypoints , will it improve the quality of the generated images?

**Comment by AliaksandrSiarohin** [comment]
It depends, if you predict more it improves up to some point. If you predict too much they can start to encode appearance.

**Comment by maliho0803** [comment]
thank you! maybe 10 keypoints in your code for human face is the best choice
