### ISSUE TITLE
expected keypoint coordinates

### ISSUE THREAD

**Issue by saandeepa93** [AliaksandrSiarohin/mtm#25]
Hello,
What is the intuition behind squishing the grid coordinates between [-1, 1] before calculating the expectation and covariance of the heatmaps? 
In the paper it is mentioned that the grid coordinates have values within the _H*W_ coordinates but in the code those values are reduced to [-1, 1]. Referring to the **make_coordinate_grid** method _under /modules/util.py_. Please let me know if I am missing something.

Thanks in advance!

**Comment by AliaksandrSiarohin** [comment]
Pytorch grid_warp method assumes that your coordinated is in [-1,1] range. So you can either use this range from the begining, like I did or use [0,W]x[0,H] range and then normalise when you pass to grid_warp. These are equivalent.

**Comment by saandeepa93** [comment]
Got it! Thank you for your quick response.
