### ISSUE TITLE
Pretrained checkpoint 

### ISSUE THREAD

**Issue by sahngmin** [AliaksandrSiarohin/mtm#35]
Thank you very much for your impressive work. 
I am interested in your work and want to use the model as a baseline of my Face Reenactment network. 
However, the downloaded model has an error (maybe it is an invalid link) when extracting the files.
Can you provide me the pre-trained model directly? 
For sure I will cite your paper on my work.
Thanks.

**Comment by AliaksandrSiarohin** [comment]
It is not arxiv, so you should not extract.
