### ISSUE TITLE
Training on custom data using pretrained weights

### ISSUE THREAD

**Issue by abhishekcodework** [AliaksandrSiarohin/mtm#36]
Firstly, great work on maintaining this repo.
I was trying to use the vox pretrained weights to train on my custom data using vox-full.yaml. But the training terminates. It shows 0/20 its and then exits.
I ran the following command (custom.yaml is based on vox-full.yaml): 
CUDA_VISIBLE_DEVICES=0 python run.py --config config/custom.yaml --checkpoint log/custom/vox-cpk.pth.tar
Also, thank you

**Comment by AliaksandrSiarohin** [comment]
Probably, you need to use 2 gpus or reduce the batch size.

**Comment by abhishekcodework** [comment]
I am able to train without providing --checkpoint with the same config but I get the follwoing error while trying to use vox pretrained weights:
![ss](https://user-images.githubusercontent.com/44052883/130293886-6553c7b7-2b65-4243-b7f3-6235ba8ccb6a.JPG)

**Comment by AliaksandrSiarohin** [comment]
There is no errors, by default it continues from the last epoch. If it already trained than it will be trained only for one epoch. Increase the number of epochs in config and adjust the lr schedule.

**Comment by abhishekcodework** [comment]
increased epochs(num_epochs) to as much as 100 from the initial 20 and changed or to lr to 1.0e-04 but still the same issue with using vox pretrained weights

**Comment by abhishekcodework** [comment]
thank you for the help. Closing this issue now
