### ISSUE TITLE
Log file - More number of lines in log file than expected

### ISSUE THREAD

**Issue by sauravns** [AliaksandrSiarohin/mtm#38]
Hi,
I had trained the MonkeyNet for 200 epochs, when I checked the log file it has 312 lines. 
Can someone explain why it is so?
Thanks in advance  :-)

**Comment by AliaksandrSiarohin** [comment]
It prints in log over fixed number of steps, it is not related to epochs if I remember correctly.

**Comment by sauravns** [comment]
sorry, what steps?

**Comment by AliaksandrSiarohin** [comment]
Train steps.

**Comment by sauravns** [comment]
Oh ok. Thank you so much
